CREATE TABLE Admins(
	AdminID INT IDENTITY(1,1) PRIMARY KEY,
	FullName NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) UNIQUE NOT NULL,
	PasswordHash NVARCHAR(255) NOT NULL,
	Role NVARCHAR(50) DEFAULT 'MANAGER',
	CreateAt DATETIME DEFAULT GETDATE()
);