CREATE SCHEMA `bookingparkingsystem` ;
-- User
CREATE TABLE Users(
	UserID INT PRIMARY KEY AUTO_INCREMENT,
	Username VARCHAR(20) NOT NULL,
	FullName VARCHAR(100) NOT NULL,
	LastName VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL UNIQUE,
	PasswordHash VARCHAR(255) NOT NULL,
	Address VARCHAR(255) NOT NULL,
	Role ENUM('CUSTOMER','ADMIN','MANAGER') NOT NULL DEFAULT 'CUSTOMER',
	CreateAt  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT CheckNameLength CHECK (CHAR_LENGTH(username) BETWEEN 3 AND 20)
);

-- Admin
CREATE TABLE Admins(
	AdminID INT PRIMARY KEY AUTO_INCREMENT,
	FullName VARCHAR(100) NOT NULL,
	Email VARCHAR(100) UNIQUE NOT NULL,
	PasswordHash VARCHAR(255) NOT NULL,
	role ENUM('MANAGER','STAFF','SUPERADMIN') NOT NULL DEFAULT 'MANAGER',
	CreateAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- Vehicle
CREATE TABLE Vehicles(
	VehID INT PRIMARY KEY AUTO_INCREMENT,
	UserID int NOT NULL,
	VehType VARCHAR(100) NOT NULL,
	PlateNum VARCHAR(100) NOT NULL,
	CreateAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vehicle_user
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
    ON DELETE CASCADE ON UPDATE CASCADE
);

-- Parking SLot
CREATE TABLE ParkingSlot(
	SlotID INT PRIMARY KEY AUTO_INCREMENT PRIMARY KEY,
	AreaID INT NOT NULL,
	SlotNum INT NOT NULL,
    currentVehID INT NULL,
	SlotLocation varchar(100),
	SlotStatus ENUM('available','not available') NOT NULL DEFAULT 'available',
    UNIQUE KEY uq_area_slot (AreaID, SlotNum),
	CONSTRAINT fk_slot_area
    FOREIGN KEY (AreaID) REFERENCES ParkingAreas(AreaID)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_slot_vehicle
    FOREIGN KEY (currentVehID) REFERENCES vehicles(VehID)
    ON DELETE SET NULL ON UPDATE CASCADE
);

-- Parking Area
Create Table ParkingAreas (
	AreaID INT PRIMARY KEY AUTO_INCREMENT,
	ParkName VARCHAR(100) not null,
	ParkingLocation VARCHAR(255),
	TotalSlots int not null,
	AvailableSlots Int not null,
	PricePerHour Decimal(10,2) not null,
	CreateAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_slots_nonneg CHECK (TotalSlots >= 0 AND AvailableSlots >= 0),
    CONSTRAINT chk_slots_cap CHECK (AvailableSlots <= TotalSlots),
    CONSTRAINT chk_price_positive CHECK (PricePerHour >= 0)
);
-- Booking
CREATE TABLE Booking (
    BookingID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    AreaID INT NOT NULL,
    SlotID  INT NOT NULL,
    SlotNumber INT,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Phone VARCHAR(50) NOT NULL,
    UserAddress VARCHAR(255) NOT NULL,
    StartTime DATETIME NOT NULL,
    EndTime DATETIME NOT NULL,
    BookingStat ENUM('PENDING','CONFIRMED','CANCELLED','COMPLETED') NOT NULL DEFAULT 'PENDING',
    CreateAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_booking_user
    FOREIGN KEY (UserID) REFERENCES users(UserID)
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_booking_area
    FOREIGN KEY (AreaID) REFERENCES ParkingAreas(AreaID)
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_booking_slot
    FOREIGN KEY (SlotID) REFERENCES ParkingSlot(SlotID)
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT chk_time_order CHECK (EndTime > StartTime)
);



-- Payment
CREATE TABLE Payment (
    transacID INT PRIMARY KEY AUTO_INCREMENT,
    transacTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UserID INT NOT NULL,
    BookingID INT NOT NULL,
    TotalCost DECIMAL(12, 0) NOT NULL, -- Price in VND, adjust precision if needed
    PayStat ENUM('Paid','Unpaid','Refunded') NOT NULL DEFAULT 'Unpaid',
    PayMethod ENUM('Online Banking', 'Credit Card', 'Pay In Cash') NOT NULL,
     CONSTRAINT fk_payment_user
    FOREIGN KEY (UserID) REFERENCES users(UserID)
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_payment_booking
    FOREIGN KEY (BookingID) REFERENCES bookings(BookingID)
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT chk_total_cost CHECK (TotalCost >= 0)
);
