CREATE TABLE Users(
	UserID INT IDENTITY(1,1) PRIMARY KEY,
	FullName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) UNIQUE NOT NULL,
	PasswordHash NVARCHAR(255) NOT NULL,
	Address NVARCHAR(255) NOT NULL,
	Role NVARCHAR(50) DEFAULT 'CUSTOMER',
	CreateAt DATETIME DEFAULT GETDATE()
);